apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: default
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      release: canary
  template:
    metadata:
      labels:
        app: myapp
        release: canary
    spec:
      containers:
      - name: myapp
        image: ekungurov/myapp:latest
        env:
        - name: DB_HOST
          value: "192.168.56.1"
        - name: DB_LOGIN
          value: "db_login"
        - name: DB_PASSWORD
          value: "some_secret_password"
        - name: DB_NAME
          value: "star_wars"
      imagePullSecrets:
      - name: regcred
